### ISSUE TITLE
WebapiError, fails after authenticating

### ISSUE THREAD

**Issue by aznd** [nlspnsgen/spotify-to-soulseek#1]
I get this error after authenticating with the link one gets.
Censoring (***) in case client id is confidential data
```
listening on port 3000
setting up Soulseek...
Soulseek Setup done.
Please click this link:  https://accounts.spotify.com/authorize?client_id=***&response_type=code&redirect_uri=http://localhost:3000/auth&scope=&state=state
Authenticated!
/home/user/spotify-to-soulseek/node_modules/spotify-web-api-node/src/http-manager.js:47
  return new WebapiError(response.body, response.headers, response.statusCode, response.body);
         ^

WebapiError: [object Object]
    at _toError (/home/user/spotify-to-soulseek/node_modules/spotify-web-api-node/src/http-manager.js:47:10)
    at /home/user/spotify-to-soulseek/node_modules/spotify-web-api-node/src/http-manager.js:71:25
    at Request.callback (/home/user/spotify-to-soulseek/node_modules/superagent/lib/node/index.js:905:3)
    at IncomingMessage.<anonymous> (/home/user/spotify-to-soulseek/node_modules/superagent/lib/node/index.js:1127:20)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  body: {},
  headers: {
    'cache-control': 'private, max-age=0',
    'access-control-allow-origin': '*',
    'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version, X-Cloud-Trace-Context, client-token, content-access-token',
    'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH',
    'access-control-allow-credentials': 'true',
    'access-control-max-age': '604800',
    'content-length': '0',
    'strict-transport-security': 'max-age=31536000',
    'x-content-type-options': 'nosniff',
    date: 'Tue, 12 Apr 2022 20:50:12 GMT',
    server: 'envoy',
    via: 'HTTP/2 edgeproxy, 1.1 google',
    'alt-svc': 'clear',
    connection: 'close'
  },
  statusCode: 404
}

Node.js v17.8.0
```

**Comment by jacks97** [comment]
Was having the same problem as you and figured out that it's a syntax issue!

So the parameter shouldn't be the full playlist URL, just the last section of the URL before the parameters. For example, if my playlist's URL is: `https://open.spotify.com/playlist/abcdefghijklmo?si=1234567` then the command I would want to use would be:
```
node index.js abcdefghijklmo
```

**Comment by nlspnsgen** [comment]
Thanks @jacks97! Gonna make a note about this on the Readme.
