### ISSUE TITLE
Error ENOENT 

### ISSUE THREAD

**Issue by Souciix** [nlspnsgen/spotify-to-soulseek#2]
Hello,

When running the node, everything goes well until the download, would you have any suggestion? :

```
PS C:\spotify-to-soulseek-main> node index.js 3f0eaFdjzcYqNmvYccKFZ6E
listening on port 3000
setting up Soulseek...
Error: ENOENT: no such file or directory, mkdir '/tmp/slsk'
    at Object.mkdirSync (node:fs:1349:3)
    at mkdirSync (C:\spotify-to-soulseek-main\node_modules\slsk-client\lib\index.js:9:8)
    at connect (C:\spotify-to-soulseek-main\node_modules\slsk-client\lib\index.js:20:5)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at connect (node:internal/util:346:12)
    at setupSlsk (C:\spotify-to-soulseek-main\downloadSong.js:14:24)
    at Server.<anonymous> (C:\spotify-to-soulseek-main\index.js:61:9)
    at Object.onceWrapper (node:events:641:28)
    at Server.emit (node:events:527:28) {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/tmp/slsk'

```

**Comment by nlspnsgen** [comment]
Hey! What OS are you running? I don't know windows systems that well but it could be that they don't have a `/tmp/` directory. In this case [this line](https://github.com/f-hj/slsk-client/blob/5507cac8757068d1946ef205c6bd0d82614dd1bc/lib/index.js#L20) from the slsk-client dependency may not work. Its a little hacky but you could go into `node_modules\slsk-client\lib\index.js` and change it to another directory.

**Comment by nlspnsgen** [comment]
Actually this seems to be a windows compatibility issue on the `slsk-client` repo. https://github.com/f-hj/slsk-client/pull/43
